---
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - nfs
    - packer-debian
    - elixir
    - postgresql
    - nodejs
    - git
    - inotify-tools
  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim

    - name: set postgres password
      postgresql_user: user=postgres password=postgres
  vars:
    elixir_version: 1.2.5
    elixir_phoenix_user: vagrant
    postgresql_version: 9.4
    nodejs_version: 5.x

