---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Debian/Ubuntu configuration for Packer.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - cloud
    - system
    - packaging
    - development
